// Render the install config into a `.env`, MERGE-PRESERVING: comments, ordering,
// and any keys we don't manage (e.g. host-generated AUTHENTIK_* secrets on a
// re-run) are left untouched. Uses the same anchored-line discipline as
// packages/compose/scripts/install.sh's env_set, so the two never fight.

import { INSTALL_SCHEMA, defaultFor, type ConfigMap, type InstallField } from './schema';

/** Parse a `.env` text into a flat map (ignores comments/blank lines). */
export function parseEnv(text: string): ConfigMap {
  const out: ConfigMap = {};
  for (const raw of text.split('\n')) {
    const line = raw.trim();
    if (!line || line.startsWith('#') || !line.includes('=')) continue;
    const eq = line.indexOf('=');
    out[line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
  }
  return out;
}

/**
 * Update `baseText` so every `key=value` in `config` is set, replacing an existing
 * `^KEY=...` line in place or appending if absent. Everything else is preserved.
 */
export function renderEnv(config: ConfigMap, baseText: string): string {
  let text = baseText;
  const appended: string[] = [];
  for (const [key, value] of Object.entries(config)) {
    const re = new RegExp(`^${escapeRe(key)}=.*$`, 'm');
    const line = `${key}=${value}`;
    if (re.test(text)) {
      // Function replacement avoids `$&`/`$1` interpretation in the value.
      text = text.replace(re, () => line);
    } else {
      appended.push(line);
    }
  }
  if (appended.length) {
    if (text.length && !text.endsWith('\n')) text += '\n';
    text += appended.join('\n') + '\n';
  }
  return text;
}

/**
 * Last-resort base used when neither an existing `.env` nor a `.env.example` is on
 * disk (e.g. `hola init` run on a laptop without a Hola checkout). Generates a
 * documented stub from the schema. In-repo runs always prefer the real template.
 */
export function schemaTemplate(): string {
  const lines = ['# Generated by `hola init`. See packages/compose/.env.example for full docs.', ''];
  for (const field of INSTALL_SCHEMA) {
    if (field.help) lines.push(`# ${field.help}`);
    lines.push(`${field.key}=${staticDefault(field)}`);
  }
  return lines.join('\n') + '\n';
}

function staticDefault(field: InstallField): string {
  // Only emit non-dynamic defaults in the stub; dynamic ones get filled by config.
  return typeof field.default === 'function' ? '' : defaultFor(field, {});
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
